apiVersion: batch/v1
kind: Job
metadata:
  name: config-init-load
spec:
  template:
    metadata:
      labels:
        app: config-init-load
    spec:
      restartPolicy: Never
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-volume-claim
      containers:
        - name: config-init-load
          image: gluufederation/config-init:4.0.0_dev
          volumeMounts:
            - mountPath: /opt/config-init/db/
              name: config
          env:
            - name: GLUU_CONFIG_ADAPTER
              value: kubernetes
            - name: GLUU_SECRET_ADAPTER
              value: kubernetes
          args: ["load"]
