apiVersion: v1
kind: Service
metadata:
  name: oxshibboleth
  labels:
    app: oxshibboleth
spec:
  ports:
  - port: 8080
    name: oxshibboleth
  selector:
    app: oxshibboleth
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oxshibboleth
  labels:
    app: oxshibboleth
spec:
  serviceName: oxshibboleth
  replicas: 1
  selector:
    matchLabels:
      app: oxshibboleth
  template:
    metadata:
      labels:
        app: oxshibboleth
    spec:
      containers:
      - name: oxshibboleth
        imagePullPolicy: Always
        image: gluufederation/oxshibboleth:latest
        resources:
          requests:
            memory: "1000Mi"
          limits:
            memory: "1536Mi"
        ports:
        - containerPort: 8080
        env:
          - name: GLUU_CONFIG_ADAPTER
            value: "kubernetes"
          - name: GLUU_LDAP_URL
            value: "opendj:1636"
          - name: GLUU_OXAUTH_BACKEND
            value: "oxauth:8080"
          - name: GLUU_MAX_RAM_FRACTION
            value: "1"
        volumeMounts:
          # name must match the volume name below
          - name: shared-shib
            mountPath: "/opt/shared-shibboleth-idp"
        livenessProbe:
          httpGet:
            path: /idp
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /idp
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 25
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - kube.gluu.local
      volumes:
      - name: shared-shib
        persistentVolumeClaim:
          claimName: shared-shib-volume-claim
