apiVersion: v1
kind: ConfigMap
metadata:
  name: cr-rotate-cm
data:
  GLUU_CONFIG_ADAPTER: "kubernetes"
  GLUU_SECRET_ADAPTER: "kubernetes"
  GLUU_LDAP_URL: "opendj:1636"
  GLUU_CONTAINER_METADATA: "kubernetes"

---

apiVersion: v1
kind: Service
metadata:
  name: cr-rotate
  labels:
    app: cr-rotate
spec:
  ports:
  - port: 8080
    name: cr-rotate
  selector:
    app: cr-rotate

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cr-rotate
  labels:
    app: cr-rotate
spec:
  selector:
    matchLabels:
      app: cr-rotate
  template:
    metadata:
      labels:
        app: cr-rotate
    spec:
      containers:
      - name: cr-rotate
        imagePullPolicy: Always
        image: gluufederation/cr-rotate:4.0.0_dev
        envFrom:
        - configMapRef:
            name: cr-rotate-cm
