apiVersion: v1
kind: Service
metadata:
  name: oxpassport
  labels:
    app: oxpassport
spec:
  ports:
  - port: 8090
    name: oxpassport
  selector:
    app: oxpassport
  # type: NodePort
  # clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxpassport
  labels:
    app: oxpassport
spec:
  # serviceName: oxpassport
  replicas: 1
  selector:
    matchLabels:
      app: oxpassport
  template:
    metadata:
      labels:
        app: oxpassport
    spec:
      containers:
      - name: oxpassport
        imagePullPolicy: Always
        image: gluufederation/oxpassport:3.1.6_dev
        ports:
        - containerPort: 8090
        env:
          - name: GLUU_CONFIG_ADAPTER
            value: "kubernetes"
          - name: GLUU_SECRET_ADAPTER
            value: "kubernetes"
        livenessProbe:
          httpGet:
            path: /passport
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /passport
            port: 8090
          initialDelaySeconds: 25
          periodSeconds: 25
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - kube.gluu.local
