apiVersion: v1
kind: ConfigMap
metadata:
  name: oxtrust-cm
data:
  GLUU_CONFIG_ADAPTER: "kubernetes"
  GLUU_SECRET_ADAPTER: "kubernetes"
  GLUU_OXAUTH_BACKEND: "oxauth:8080"
  GLUU_LDAP_URL: "opendj:1636"
  GLUU_MAX_RAM_FRACTION: "1"
  DOMAIN: "kube.gluu.local"

---

apiVersion: v1
kind: Service
metadata:
  name: oxtrust
  labels:
    app: oxtrust
spec:
  ports:
  - port: 8080
    name: oxtrust
  selector:
    app: oxtrust
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oxtrust
  labels:
    app: oxtrust
    APP_NAME: oxtrust
spec:
  serviceName: oxtrust
  replicas: 1
  selector:
    matchLabels:
      app: oxtrust
  template:
    metadata:
      labels:
        app: oxtrust
        APP_NAME: oxtrust
    spec:
      containers:
      - name: oxtrust
        imagePullPolicy: Always
        image: gluufederation/oxtrust:4.0.0_dev
        resources:
          requests:
            memory: "1000Mi"
          limits:
            memory: "1536Mi"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: oxtrust-cm
        volumeMounts:
          # name must match the volume name below
          - name: shared-shib
            mountPath: "/opt/shared-shibboleth-idp"
          - mountPath: /opt/gluu/jetty/identity/logs
            name: oxtrust-logs
          - mountPath: /opt/gluu/jetty/identity/lib/ext
            name: oxtrust-lib-ext
          - mountPath: /opt/gluu/jetty/identity/custom/static
            name: oxtrust-custom-static
          - mountPath: /opt/gluu/jetty/identity/custom/pages
            name: oxtrust-custom-pages
        livenessProbe:
          httpGet:
            path: /identity/restv1/scim-configuration
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /identity/restv1/scim-configuration
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 25
      hostAliases:
      - ip: NGINX_IP
        hostnames:
        - kube.gluu.local
      volumes:
      - name: shared-shib
        persistentVolumeClaim:
          claimName: shared-shib-volume-claim
      - name: oxtrust-logs
        persistentVolumeClaim:
          claimName: oxtrust-logs-volume-claim
      - name: oxtrust-lib-ext
        persistentVolumeClaim:
          claimName: oxtrust-lib-ext-volume-claim
      - name: oxtrust-custom-static
        persistentVolumeClaim:
          claimName: oxtrust-custom-static-volume-claim
      - name: oxtrust-custom-pages
        persistentVolumeClaim:
          claimName: oxtrust-custom-pages-volume-claim
