apiVersion: v1
kind: ConfigMap
metadata:
  name: key-rotation-cm
data:
  GLUU_CONFIG_ADAPTER: "kubernetes"
  GLUU_SECRET_ADAPTER: "kubernetes"
  GLUU_LDAP_URL: "opendj:1636"

---

apiVersion: v1
kind: Service
metadata:
  name: key-rotation
  labels:
    app: key-rotation
spec:
  ports:
  - port: 8080
    name: key-rotation
  selector:
    app: key-rotation

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-rotation
  labels:
    app: key-rotation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: key-rotation
  template:
    metadata:
      labels:
        app: key-rotation
    spec:
      containers:
      - name: key-rotation
        imagePullPolicy: Always
        image: gluufederation/key-rotation:4.0.0_dev
        envFrom:
        - configMapRef:
            name: key-rotation-cm
